#!/bin/bash
#
# Open3G Shell Version
# title           :open3gs
# file            :open3gs
# description     :This script will handle 3g connections
# author          :protetore
# date            :20150620
# version         :0.1
# usage           :bash open3gs [operator|status|setup] [-r]
# bash_version    :4.1.5(1)-release
#=============================================================

BASE_DIR=$(dirname $(/bin/readlink -f $0))
#. $BASE_DIR/variables.sh
. $BASE_DIR/functions.sh

$ECHO
$ECHO "~~~ Open3G Shell Connector ~~~"
$ECHO

typeset -A FUNCTIONS
FUNCTIONS[c]="connect"
FUNCTIONS[d]="disconnect"
FUNCTIONS[r]="reconnect"
FUNCTIONS[s]="status"
FUNCTIONS[i]="install"
FUNCTIONS[n]="reconfigure"
FUNCTIONS[h]="help"

functionName=""
aways=1
configPath=""

while getopts ":cdrsinhaf:" opt; do
  case $opt in
    c)
      functionName=${FUNCTIONS[$opt]}
      ;;
    a)
      aways=0
      ;;
    f)
      configPath=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# Options
case "$functionName" in
    "connect")
        connect $aways $configPath
        retval=$?
        ;;
    "disconnect")
        disconnect
        retval=$?
        ;;
    "reconnect")
        reconnect $aways $configPath
        retval=$?
        ;;
    "status")
        connStatus
        retval=$?
        ;;
    "reconfigure")
        reconfigure $configPath
        retval=$?
        ;;
    "install")
        install
        retval=$?
        ;;
    "help")
        usage
        retval=1
        ;;
    *)
        usage
        retval=$?
esac

$ECHO
